-- CREATE TABLE

-- DB1B TICKET 
CREATE TABLE ticket_2019 (
ItinId BIGINT NOT NULL,
Coupons INT,
_Year INT,
_Quarter INT,
Origin VARCHAR(255),
OriginAirportID INT,
OriginAirportSeqID INT,
OriginCityMarketID INT,
OriginCountry VARCHAR(255),
OriginStateFips INT,
OriginState VARCHAR(255),
OriginStateName VARCHAR(255),
OriginWac INT,
RoundTrip FLOAT,
_OnLine FLOAT,
DollarCred INT,
FarePerMile FLOAT,
RPCarrier VARCHAR(255),
Passengers FLOAT,
ItinFare FLOAT,
BulkFare FLOAT,
Distance FLOAT,
DistanceGroup INT,
MilesFLown FLOAT,
ItinGeoType INT,
Unnamed VARCHAR(255),
PRIMARY KEY (ItinID)
);

CREATE TABLE ticket_2018 (
ItinId BIGINT NOT NULL,
Coupons INT,
_Year INT,
_Quarter INT,
Origin VARCHAR(255),
OriginAirportID INT,
OriginAirportSeqID INT,
OriginCityMarketID INT,
OriginCountry VARCHAR(255),
OriginStateFips INT,
OriginState VARCHAR(255),
OriginStateName VARCHAR(255),
OriginWac INT,
RoundTrip FLOAT,
_OnLine FLOAT,
DollarCred INT,
FarePerMile FLOAT,
RPCarrier VARCHAR(255),
Passengers FLOAT,
ItinFare FLOAT,
BulkFare FLOAT,
Distance FLOAT,
DistanceGroup INT,
MilesFLown FLOAT,
ItinGeoType INT,
Unnamed VARCHAR(255),
PRIMARY KEY (ItinID)
);

-- DB1B MARKET 
CREATE TABLE market_2019 (
ItinID BIGINT NOT NULL,
MktID BIGINT NOT NULL,
MktCoupons INT,
_Year INT,
_Quarter INT,
OriginAirportID INT,
OriginAirportSeqID INT,
OriginCityMarketID INT,
Origin VARCHAR(255),
OriginCountry VARCHAR(255),
OriginStateFips INT,
OriginState VARCHAR(255),
OriginStateName VARCHAR(255),
OriginWac INT,
DestAirportID INT,
DestAirportSeqID INT,
DestCityMarketID INT,
Dest VARCHAR(255),
DestCountry VARCHAR(255),
DestStateFips INT,
DestState VARCHAR(255),
DestStateName VARCHAR(255),
DestWac INT,
AirportGroup VARCHAR(255),
WacGroup VARCHAR(255),
TkCarrierChange FLOAT, 
TkCarrierGroup VARCHAR(255),
OpCarrierChange FLOAT,
OpCarrierGroup VARCHAR(255),
RPCarrier VARCHAR(255),
TkCarrier VARCHAR(255), 
OpCarrier VARCHAR(255),
BulkFare FLOAT,
Passengers FLOAT,
MktFare FLOAT, 
MktDistance FLOAT,
MktDistanceGroup INT,
MktMilesFlown FLOAT,
NonStopMiles FLOAT,
ItinGeoType INT,
MktGeoType INT,
Unnamed VARCHAR(255),
PRIMARY KEY (MktID)
);

CREATE TABLE market_2018 (
ItinID BIGINT NOT NULL,
MktID BIGINT NOT NULL,
MktCoupons INT,
_Year INT,
_Quarter INT,
OriginAirportID INT,
OriginAirportSeqID INT,
OriginCityMarketID INT,
Origin VARCHAR(255),
OriginCountry VARCHAR(255),
OriginStateFips INT,
OriginState VARCHAR(255),
OriginStateName VARCHAR(255),
OriginWac INT,
DestAirportID INT,
DestAirportSeqID INT,
DestCityMarketID INT,
Dest VARCHAR(255),
DestCountry VARCHAR(255),
DestStateFips INT,
DestState VARCHAR(255),
DestStateName VARCHAR(255),
DestWac INT,
AirportGroup VARCHAR(255),
WacGroup VARCHAR(255),
TkCarrierChange FLOAT, 
TkCarrierGroup VARCHAR(255),
OpCarrierChange FLOAT,
OpCarrierGroup VARCHAR(255),
RPCarrier VARCHAR(255),
TkCarrier VARCHAR(255), 
OpCarrier VARCHAR(255),
BulkFare FLOAT,
Passengers FLOAT,
MktFare FLOAT, 
MktDistance FLOAT,
MktDistanceGroup INT,
MktMilesFlown FLOAT,
NonStopMiles FLOAT,
ItinGeoType INT,
MktGeoType INT,
Unnamed VARCHAR(255),
PRIMARY KEY (MktID)
);

-- DB1B COUPON
CREATE TABLE coupon_2018 (
ItinID BIGINT NOT NULL,
MktID BIGINT NOT NULL,
SeqNum BIGINT,
Coupons INT,
_Year INT,
OriginAirportID INT,
OriginAirportSeqID INT,
OriginMarketID INT,
_Quarter INT,
Origin VARCHAR(255),
OriginCountry VARCHAR(255),
OriginStateFips INT,
OriginState VARCHAR(255),
OriginStateName VARCHAR(255),
OriginWac INT,
DestAirportID INT,
DestAirportSeqID INT,
DestCityMarketID INT,
Dest VARCHAR(255),
DestCountry VARCHAR(255),
DestStateFips INT,
DestState VARCHAR(255),
DestStateName VARCHAR(255),
DestWac INT,
Break VARCHAR(255),
CouponType VARCHAR(255),
TkCarrier VARCHAR(255),
OpCarrier VARCHAR(255),
RPCarrier VARCHAR(255),
Passengers FLOAT,
FareClass VARCHAR(255),
Distance FLOAT,
DistanceGroup INT,
Gateway FLOAT,
ItinGeoType INT,
CouponGeoType INT,
Unnamed VARCHAR(255),
PRIMARY KEY (MktID)
);

CREATE TABLE coupon_2019 (
ItinID BIGINT NOT NULL,
MktID BIGINT NOT NULL,
SeqNum BIGINT,
Coupons INT,
_Year INT,
OriginAirportID INT,
OriginAirportSeqID INT,
OriginMarketID INT,
_Quarter INT,
Origin VARCHAR(255),
OriginCountry VARCHAR(255),
OriginStateFips INT,
OriginState VARCHAR(255),
OriginStateName VARCHAR(255),
OriginWac INT,
DestAirportID INT,
DestAirportSeqID INT,
DestCityMarketID INT,
Dest VARCHAR(255),
DestCountry VARCHAR(255),
DestStateFips INT,
DestState VARCHAR(255),
DestStateName VARCHAR(255),
DestWac INT,
Break VARCHAR(255),
CouponType VARCHAR(255),
TkCarrier VARCHAR(255),
OpCarrier VARCHAR(255),
RPCarrier VARCHAR(255),
Passengers FLOAT,
FareClass VARCHAR(255),
Distance FLOAT,
DistanceGroup INT,
Gateway FLOAT,
ItinGeoType INT,
CouponGeoType INT,
Unnamed VARCHAR(255),
PRIMARY KEY (MktID)
);
 